// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcshcafyiyghfokbokyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjc2hjYWZ5aXlnaGZva2Jva3l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjI4NjQsImV4cCI6MjA2MjQzODg2NH0.bqAhFNrzqDWqESmsxX8eKIdYpScPo4_IbjcHw6koqLE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);