name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git subtree
          token: ${{ secrets.DEPLOY_TOKEN }}  # Use the token for checkout

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Configure git to use the token
          git remote set-url origin https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ github.repository }}
          
          # Create or reset gh-pages branch
          git checkout --orphan gh-pages-temp || git checkout -b gh-pages-temp
          
          # Remove everything except .git and dist
          git ls-files | grep -v "dist" | xargs git rm -f || true
          
          # Move dist contents to root
          if [ -d "dist" ]; then
            # Move all files from dist to root
            cp -r dist/* .
            # Remove dist directory
            rm -rf dist
            # Add all files
            git add .
            # Commit the changes
            git commit -m "Deploy (GitHub Actions) - $(date +'%Y-%m-%d %H:%M:%S')"
            # Force push to gh-pages branch
            git push origin gh-pages-temp:gh-pages --force
          else
            echo "Error: dist directory not found"
            exit 1
          fi
          
          # Clean up
          git checkout main
          git branch -D gh-pages-temp
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }} 