name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git subtree
          token: ${{ secrets.DEPLOY_TOKEN }}  # Use the token for checkout

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Configure git to use the token
          git remote set-url origin https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ github.repository }}
          
          # Remove the dist directory from gitignore if it's there
          sed -i '/dist/d' .gitignore || true
          
          # Create or reset gh-pages branch
          git checkout --orphan gh-pages-temp || git checkout -b gh-pages-temp
          git rm -rf .
          
          # Add the dist directory
          git add dist -f
          
          # Move dist contents to root
          git mv dist/* .
          git rm -rf dist
          
          # Commit the changes
          git commit -m "Deploy (GitHub Actions) - $(date +'%Y-%m-%d %H:%M:%S')"
          
          # Force push to gh-pages branch
          git push origin gh-pages-temp:gh-pages --force
          
          # Clean up
          git checkout main
          git branch -D gh-pages-temp
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }} 